# Generated by Django 3.2.4 on 2021-06-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pin_code', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('request_received', models.CharField(max_length=20)),
            ],
        ),
    ]
