# Generated by Django 3.2.4 on 2021-06-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=500)),
            ],
        ),
    ]
