# Generated by Django 3.2.4 on 2021-06-29 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 6, 29, 7, 16, 18, 151495, tzinfo=utc))),
            ],
        ),
    ]
