# Generated by Django 3.2.4 on 2021-06-29 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('panid', models.CharField(max_length=100)),
                ('req_date', models.DateField(default=datetime.datetime(2021, 6, 29, 10, 50, 42, 755113, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 10, 50, 42, 627062, tzinfo=utc)),
        ),
    ]
